name: Helm PR Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    name: Helm Chart Lint
    env:
      CT_CHART_DIRS: charts
      CT_TARGET_BRANCH: $GITHUB_BASE_REF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Fake validator
        run: |
          ls -la
          echo "Faking validator"
